// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy0eqknH8BHWAXdgD2pjijW049E_R3Eg0',
    appId: '1:988752166321:web:79bc36532f1daa08f9d190',
    messagingSenderId: '988752166321',
    projectId: 'hafalan-quran-f2816',
    authDomain: 'hafalan-quran-f2816.firebaseapp.com',
    storageBucket: 'hafalan-quran-f2816.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKVuZsD-lHUxKYb7dAAvJwp2KpjeOS9Dg',
    appId: '1:988752166321:android:eb9fa50e26db4680f9d190',
    messagingSenderId: '988752166321',
    projectId: 'hafalan-quran-f2816',
    storageBucket: 'hafalan-quran-f2816.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lwKHkfdSOehTNaGmakCYVonvYmZyvBQ',
    appId: '1:988752166321:ios:6c3cf61598213500f9d190',
    messagingSenderId: '988752166321',
    projectId: 'hafalan-quran-f2816',
    storageBucket: 'hafalan-quran-f2816.firebasestorage.app',
    iosBundleId: 'com.pesantren.hafalanQuran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_lwKHkfdSOehTNaGmakCYVonvYmZyvBQ',
    appId: '1:988752166321:ios:6c3cf61598213500f9d190',
    messagingSenderId: '988752166321',
    projectId: 'hafalan-quran-f2816',
    storageBucket: 'hafalan-quran-f2816.firebasestorage.app',
    iosBundleId: 'com.pesantren.hafalanQuran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy0eqknH8BHWAXdgD2pjijW049E_R3Eg0',
    appId: '1:988752166321:web:0e1c9388b0ae7abcf9d190',
    messagingSenderId: '988752166321',
    projectId: 'hafalan-quran-f2816',
    authDomain: 'hafalan-quran-f2816.firebaseapp.com',
    storageBucket: 'hafalan-quran-f2816.firebasestorage.app',
  );
}
